# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
###########################
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: user
          POSTGRES_DB: book_store
        #volumes:
        #  - /rdb/init.psql:/docker-entrypoint-initdb.d/init.sql
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck//
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    
    steps:
    - name: where are we
      run: pwd
    #- uses: actions/checkout@v1
    #  with:
    #    # Disabling shallow clone is recommended for improving relevancy of reporting
    #    fetch-depth: 0
    #- name: Set up JDK 1.8
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: 1.8
    #- name: Cache Maven packages
    #  uses: actions/cache@v1
    #  with:
    #    path: ~/.m2
    #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #    restore-keys: ${{ runner.os }}-m2
    #- name: Test main project
    #  run: mvn clean verify sonar:sonar --file bestofbooks/pom.xml -Dsonar.projectKey=gabsw -Dsonar.organization=gabsw -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book_store

